version: '3'
networks:
  backend:
    driver: ${NETWORKS_DRIVER}

services:
  mysql:
    container_name: mysql
    image: mysql:5.7.11
    environment:
      - TZ=${TZ}
      - MYSQL_USER=${MYSQL_USERNAME}                 
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}             
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}    
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_RANDOM_ROOT_PASSWORD=0
      - MYSQL_ROOT_HOST=${MYSQL_ROOT_HOST}
    volumes:
      - ${SQL_PATH_HOST}:/var/lib/mysql       
    ports:
      - "${MYSQL_PORT}:3306"                     
    networks:
      - backend
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci