version: '3'
    
networks:
  ObjectStorageNetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/30


services:
  minio:
    image: minio/minio
    volumes:
      - ./data:/data
    environment:
      MINIO_ROOT_USER: username
      MINIO_ROOT_PASSWORD: changeme
      MINIO_SERVER_URL: 'https://s3.service'
      MINIO_BROWSER_REDIRECT_URL: 'https://admin.s3.service'
    command: server --console-address ":9080" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9080/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      ObjectStorageNetwork:
        ipv4_address: '192.168.0.2'
